### ISSUE TITLE
[iOS] Self video view has a wrong aspect ratio in portrait

### ISSUE THREAD

**Issue by ivanbellalopez** [pexip/pexkit-sdk#42]
I haven't figured a way to display correctly the `videoSelfView` in portrait. It looks like the aspect ratio is wrong even playing with the frame of the view (and layer) and the GL view is somehow stretched.

Do you know if it's a known issue or how to adapt the view after rotating the device?

I attach some screenshot showing the problem.

Landscape
![pexip_landscape](https://cloud.githubusercontent.com/assets/1830073/17146945/bf54a294-5360-11e6-8cb9-c280d4b6794a.PNG)

Portrait
![pexip_portrait](https://cloud.githubusercontent.com/assets/1830073/17146944/bf3a27a2-5360-11e6-9168-84afb5aaf18c.PNG)

Note: I also tried changing the value for `[UIView contentMode]` in `videoSelfView`.

**Comment by zaichang** [comment]
Here's an example of the fix that someone made on their webrtc app:
https://github.com/ISBX/apprtc-ios/commit/512b1471dbcf6bb15fef82aeecfc66d39c1c597b

My guess is that the Pexkit code needs something similar.

In WebRTC's example itself, [their fix (2 years ago)](https://review.webrtc.org/8479005/patch/210001/220012) was a simple swapping of width and height depending on orientation, which seems reasonable:

    CGFloat localVideoViewWidth = UIInterfaceOrientationIsPortrait(self.statusBarOrientation) ? 
                                       screenSize.width/4 : screenSize.height/4;
    CGFloat localVideoViewHeight = UIInterfaceOrientationIsPortrait(self.statusBarOrientation) ? 
                                       screenSize.height/4 : screenSize.width/4;
    
Given the state of the current Pexip app, I think it can still be temporarily fixed by the client by using UIView.transform when in portrait mode. It shouldn't be the long term solution though, I ought to point out.

**Comment by miguelsanchez** [comment]
Continuing with this issue. It looks like the problem is not really the aspect ratio that the video has but the actual portion of the video that is transmitted.

In this couple of snapshots we can see how the local video (in portrait mode with the right aspect ratio) gets only represented in its middle part on another device receiving that video:

Emitter (consider the video with a painting in it):
![img_0852](https://cloud.githubusercontent.com/assets/777163/17897156/747128e8-6953-11e6-832b-fad00b5f8b46.PNG)

Receiver:
![img_0084](https://cloud.githubusercontent.com/assets/777163/17897190/927eca2a-6953-11e6-8ae9-a80001c8f9d9.PNG)


Whereas when the device is in landscape mode most of the video is transmitted. I say most, because I've noticed that the borders of the video are also cropped.

![img_0853](https://cloud.githubusercontent.com/assets/777163/17897294/f184bb6a-6953-11e6-8d6c-1fad3bd0a871.PNG)

Receiver (this snapshot wasn't very well done but while taking it I could see the painting from side to side):
![img_0085](https://cloud.githubusercontent.com/assets/777163/17897300/f55e412a-6953-11e6-8db2-9687d31d0f9a.PNG)

I am not exactly sure who is cropping the video when taken in portrait mode but since it is happening in Android, too, I guess it is the server side. If the server cannot be changed so that the video is pillar boxed if needed, we could consider masking the local video view in order to show exactly what is transmitted, but we would need to know what is inner frame of the video.

**Comment by zaichang** [comment]
To be clear, I think there are two issues here and the second one we discovered while researching the first.

1. The aspect ratio of the self view is wrong in portrait mode in iOS because the view controller is not resizing the self view on rotation.

2. The second one is the server's interpretation on receiving the portrait video signal is to crop it to fit the existing video aspect ratio rather than displaying the entire frame of the portrait stream.

This filed issue here is about the aspect ratio issue (thus squishing of people's faces).

**Comment by miguelsanchez** [comment]
Then the issue in our side not the SDK, so this issue can be closed and open a new one for the cropping issue.

**Comment by ivanbellalopez** [comment]
Won't fix
