### ISSUE TITLE
Video pausing and lagging on Android 7

### ISSUE THREAD

**Issue by zaichang** [pexip/pexkit-sdk#47]
We're noticing a performance decline after upgrading a Nexus 9 to Android 7, compared with it's performance previously running Android M. The key symptom is the remote video view would pause for a few seconds, before jumping to within 1 second of the current frame.

The lag compared with other devices such as Nexus 7 running Android 6 (using a video feed with a timer) is substantial and can be as much as 8 seconds (usually 2-3 seconds) before it catches up by skipping to the current frame.

Has anyone else noticed this? And if so is there a fix for the issue?

**Comment by DengueTim** [comment]
Hey Zai,
  This is an issue with the Nvidia VP8 hardware decoder on the Nexus 9.  It also happens if the device is running Android 6.  I suspect it affects other Nvidia Tegra K1 devices too.

Going forward, a fix would be to use a new version of libjingle and call `MediaCodecVideoDecoder.disableVp8HwCodec();`
on devices with Nvidia VP8 hardware support.  Unfortunately the WebRTC API has changed between versions 10111 and the latest, so some changes to the Pexip code will also be needed.

For now it's probably possible to rebuild the 10111 version of libjingle.aar but remove `'OMX.Nvidia.'` from the list  `supportedVp8HwCodecPrefixes` in `MediaCodecVideoDecoder.java`.  In theory only the libjingle_peerconnection.jar needs to be updated and the .aar re-packed.

Encoding doesn't seem to have hardware support in the current version of WebRTC.

**Comment by ianmorty** [comment]
These SDK's are now deprecated and i'd suggest moving over to the new methods as outlined in the guides thus giving you full control over every aspect of the connection.
