### ISSUE TITLE
Deprecated SDKs

### ISSUE THREAD

**Issue by charleswlee** [pexip/pexkit-sdk#59]
What would be the best way to implement pexip video inside of an iOS or Android app without using the SDK since it is now deprecated? 

Are you planning on open sourcing the framework?

**Comment by ianmorty** [comment]
Hi @charleswlee, we'll be providing documentation and examples on how to fully exercise the client targeting Q1 2017 for final versions although we'll start to put basic docs out sooner.

We'll make the announcement on this site.

**Comment by zaichang** [comment]
@charleswlee I had this question too.

I would propose that we make it a community effort, much like many of the open source SDK for Twitter or Facebook. There could be some overhead in determining architecture, dependencies and style, but I believe it is better to combine efforts so that we don't duplicate the same work over many teams.

Who else would be interested in such an effort?

@ianmorty Can you link to this issue from the README.md so that developers know to come here to join the discussion?

**Comment by ianmorty** [comment]
Yep, so fostering a development community around these examples would be very good.  We'll be posting the docs and code examples "soon" once the basics are in place.  Internally, we're discussing the best methods for communicating this out.
